name: '${pluginName}'
version: '${version}'
main: org.yuemi.example.plugin.ExamplePlugin
authors: [${authors}]
contributors: [${contributors}]
api-version: '${apiVersion}'

bstats-id: '${bstatsPluginId}'
